basePath: /api/kubecenter
definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    name: Ian Zhang
  description: This webapp is for managing the k8s resources
  title: Kubecenter API doc
  version: "1.0"
paths:
  /pods:
    get:
      consumes:
      - application/json
      description: get the pods list and name spaces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: get the pods list
      tags:
      - pods
  /pods/namespacelist:
    get:
      consumes:
      - application/json
      description: get the namespace list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: get the namespace list
      tags:
      - pods
swagger: "2.0"
